config/routes.rb
Rails.application.routes.draw do
  get 'cities/index'

  resources :cities, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    belongs_to :state

    validates :name, presence: true, uniqueness: { scope: :state, message: 'should be unique within the same state' }
    validates :state, presence: true
    validates :name, length: { minimum: 2, maximum: 100 }

    def full_name
        "#{name}, #{state.name}"
    end

    scope :by_state, ->(state_id) { where(state_id: state_id) if state_id.present? } || all
end

app/models/state.rb
class State < ApplicationRecord
  has_many :cities

  validates :name, presence: true
  validates :abbreviation, presence: true, length: { is: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
#frozen_string_literal: true

class CitiesController < ApplicationController
  def index
    @cities = City.all

    if params[:state].present? || params[:name].present?
      @cities = @cities.joins(:state)

      if params[:state].present?
        @cities = @cities.where('states.name ILIKE ?', "%#{params[:state]}%")
      end

      if params[:name].present?
        @cities = @cities.where('cities.name ILIKE ?', "%#{params[:name]}%")
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cidades</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
<div class="container">
  <h1 class="title">Cidades | Gustavo Ruiz, atividade Embarca</h1>

  <%= form_tag cities_path, method: :get, class: "form" do %>
    <div class="input-container">
      <%= label_tag :state, 'Estado', class: "label" %>
      <%= text_field_tag :state, params[:state], class: "input-field" %>
    </div>
    <div class="input-container">
      <%= label_tag :name, 'Nome da Cidade', class: "label" %>
      <%= text_field_tag :name, params[:name], class: "input-field" %>
    </div>
    <div>
      <%= submit_tag 'Buscar', class: "submit-button" %>
    </div>
  <% end %>

  <h2 class="results-title">Resultados</h2>
  <table class="results-table">
    <thead>
    <tr>
      <th>Nome da Cidade</th>
      <th>Estado</th>
    </tr>
    </thead>
    <tbody>
    <% @cities.each do |city| %>
      <tr class="result-item">
        <td><%= city.name %></td>
        <td><%= city.state.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmbarcaBackEndTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>